---
ID: "fae17c79-58b8-4cee-b45c-97cc7963e1c2"
Parent: "abe62e34-ef31-4909-aef0-c7d958393e72"
Template: "abe62e34-ef31-4909-aef0-c7d958393e72"
Path: /sitecore/templates/Project/Playground/Learning/Overrides/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210326T174012Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
