// <autogenerated>
//   This file was generated by T4 code generator Templates.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Learn.Helix.Foundation.Product.Models
{
  using System;
  using System.Collections.Generic;
  using System.Collections.Specialized;
  
  using global::Glass.Mapper.Sc.Configuration;
  using global::Glass.Mapper.Sc.Configuration.Attributes;
  using global::Glass.Mapper.Sc.Fields;
    
  using Sitecore.Data;
  using Learn.Helix.Foundation.ORM.Models;
  /// <summary>
  /// Represents const IDs for mapped type.
  /// </summary>
  public partial struct Templates
  {
   #region Template Ids
    public struct Product
    {
      public const string Id = "{3A0788CB-A090-45B8-A9F7-2874A3526A34}";
      public static ID TemplateId { get; } = new ID(Id);

      public struct Fields
      {
        public const string ProductName = "{5F49D7C3-853D-42F7-8035-84AB97BCC5B9}";
        public const string ProductPackshot = "{B80D96D6-1DBC-4021-80F9-741FB6490556}";
        public const string ProductSubTitle = "{FAC3E9BE-AA1A-4E9F-98E8-5AAC38CBBBA9}";
        public const string ProductTitle = "{1338CA47-B8D6-4287-8CCC-66733D557BF5}";
        public const string ProductDescription = "{29977420-4075-4C1E-8187-207C81FBD327}";
        public const string ProductPrice = "{8D91F241-59A1-40EB-987B-645B4693A495}";
        public const string ProductShortDescription = "{B4AF51A5-A0C2-4F5E-88A5-AD9EB8AD583B}";
      }

      public struct FieldIds
      {
        public static ID ProductName { get; } = new ID(Fields.ProductName);
        public static ID ProductPackshot { get; } = new ID(Fields.ProductPackshot);
        public static ID ProductSubTitle { get; } = new ID(Fields.ProductSubTitle);
        public static ID ProductTitle { get; } = new ID(Fields.ProductTitle);
        public static ID ProductDescription { get; } = new ID(Fields.ProductDescription);
        public static ID ProductPrice { get; } = new ID(Fields.ProductPrice);
        public static ID ProductShortDescription { get; } = new ID(Fields.ProductShortDescription);
      }
    }
    #endregion
  }

  /// <summary>
  /// Represents a mapped type for item {3A0788CB-A090-45B8-A9F7-2874A3526A34} in Sitecore.
  /// Path: /sitecore/templates/Foundation/Product/_Product
  /// </summary>
  [SitecoreType(TemplateId = Templates.Product.Id, EnforceTemplate = SitecoreEnforceTemplate.TemplateAndBase)]
  public partial interface IProduct : IGlassBase
  {
    #region Product Header

    [SitecoreField(FieldId = Templates.Product.Fields.ProductName)]
    string ProductName { get; set; }

    [SitecoreField(FieldId = Templates.Product.Fields.ProductPackshot)]
    Image ProductPackshot { get; set; }

    [SitecoreField(FieldId = Templates.Product.Fields.ProductSubTitle)]
    string ProductSubTitle { get; set; }

    [SitecoreField(FieldId = Templates.Product.Fields.ProductTitle)]
    string ProductTitle { get; set; }

	#endregion

    #region Product Sub Info

    [SitecoreField(FieldId = Templates.Product.Fields.ProductDescription)]
    string ProductDescription { get; set; }

    [SitecoreField(FieldId = Templates.Product.Fields.ProductPrice)]
    string ProductPrice { get; set; }

    [SitecoreField(FieldId = Templates.Product.Fields.ProductShortDescription)]
    string ProductShortDescription { get; set; }

	#endregion

  }
}
