---
ID: "e9fa04b7-0f9a-4c97-8112-68c436c50f98"
Parent: "844ac37d-1132-4ff5-bd72-dbcc7ed08ba9"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Project/Playground/Learning/Content Types/Product
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210419T191653Z
